apiVersion: apps/v1
kind: Deployment
metadata:
  name: node1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node1
  template:
    metadata:
      labels:
        app: node1
    spec:
      containers:
      - name: node1
        image: sultanhassan/node1-service
        ports:
        - containerPort: 50051
