apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: node1-service
spec:
  selector:
    app: node1
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: node2-service
spec:
  selector:
    app: node2
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
